# Generated by Django 5.1.3 on 2024-11-28 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_category_museum_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Museum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='staticpages.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='Desconhecido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='museus',
            field=models.ManyToManyField(related_name='eventos', to='staticpages.post'),
        ),
    ]
