# Generated by Django 5.1.3 on 2024-12-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_delete_museum_remove_post_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='museus',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
