# Generated by Django 5.1.3 on 2024-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='Desconhecido'),
            preserve_default=False,
        ),
    ]
