# Generated by Django 5.1.3 on 2024-12-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='museum',
        ),
        migrations.AddField(
            model_name='ticket',
            name='museums',
            field=models.ManyToManyField(related_name='tickets', to='post.post'),
        ),
    ]
